name: deploy-with-release
on:
  # push:
  #   branches:
  #       - main
  workflow_dispatch:
jobs:
  deploy_api:
      runs-on: ubuntu-latest 
      name: 'Deploy API'
      steps:
        - run: echo "Deploying API"
          shell: bash

  semantic_release:
    runs-on: ubuntu-latest 
    name: 'Deploy API'
    steps:

    - name: Checkout full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up GitHub CLI
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y gh

    - name: Authenticate gh
      shell: bash
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Run Semantic Release Logic
      shell: bash
      run: |
         chmod +x ./github/workflows/entrypoint.sh 
         bash ./github/workflows/entrypoint.sh 
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"