name: deploy-with-release
on:
  # push:
  #   branches:
  #       - main
  workflow_dispatch:
jobs:
  deploy_api:
      runs-on: ubuntu-latest 
      name: 'Deploy API'
      steps:
        - run: echo "Deploying API"
          shell: bash

  semantic_release:
    runs-on: ubuntu-latest
    needs: deploy_api
    permissions:
      contents: write
    steps:
      - uses: johnfdominguezrendon/github-actions-shared-personal@main/build/gh-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    