name: Manual Semantic Release

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: echo "Deploying to production"

  semantic_release:
    runs-on: ubuntu-latest
    needs: deploy_to_prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history and tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next patch version
        id: next_version
        run: |
          version=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          next_tag="v$major.$minor.$patch"
          echo "NEW_TAG=$next_tag" >> $GITHUB_ENV

      - name: Generate changelog from last tag
        run: |
          log=$(git log ${{ env.LATEST_TAG }}..HEAD --pretty=format:"- %s" --no-merges)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$log" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body: ${{ env.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
