name: turbo-repo-workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

    deploy_api:
        runs-on: ubuntu-latest 
        name: 'Deploy API'
        steps:
          - run: sleep 60
            shell: bash

    postman_tests:
        concurrency:
          group: main-${{ github.workflow }}-${{ github.job }}
          cancel-in-progress: false
        runs-on: ubuntu-latest   # coment
        name: 'Run Postman Tests'
        needs: deploy_api
        steps:
          - run: sleep 120
            shell: bash

    deploy_ui:
        runs-on: ubuntu-latest
        name: 'Deploy UI'
        needs: [deploy_api]
        environment: production
        steps:
          - run: sleep 60
            shell: bash



