name: turbo-repo-workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: main-${{ github.workflow }}  # same group per workflow on main comment
  cancel-in-progress: true         
jobs:

    deploy_api:
        runs-on: ubuntu-latest 
        name: 'Deploy API'
        steps:
          - run: sleep 60
            shell: bash

    deploy_ui:
        runs-on: ubuntu-latest
        name: 'Deploy UI'
        needs: [deploy_api]
        environment: production
        steps:
          - run: sleep 60
            shell: bash



